name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main

jobs:
  sync_to_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main

      - name: Sync to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://huggingface.co/spaces/binarysameer/Search_Engine_llama
